/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xmv.solutions.IT2JZ.GUI;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingWorker;
import xmv.solutions.IT2JZ.Jira.Excel2TestcaseConverter;
import xmv.solutions.IT2JZ.Jira.Jira;
import xmv.solutions.IT2JZ.Jira.JiraTestcase;
import xmv.solutions.commons.ExcelFile;

/**
 *
 * @author David Koller XMV Solutions GmbH
 */
public class mainGUI extends javax.swing.JFrame implements PropertyChangeListener {

    /**
     * Jira Object
     */
    private Jira jira;

    /**
     * True if Browser opened and works
     */
    private boolean browserWorks = false;

    /**
     * Creates new form mainGUI
     */
    public mainGUI() {
        initComponents();
        jira = null;

        Settings settings = Settings.getInstance();

        updateActiveStatusForExportButton();
        updateActiveStatusForLoadButton();

        jProgressBar1.setValue(0);
        jProgressBar1.setMaximum(100);
        jProgressBar1.setMinimum(0);
        jProgressBar1.setStringPainted(true);

        selectBrowser.setSelectedItem(
                Jira.Browser.valueOf(
                        settings.getProperty(
                                Settings.Keys.Browser.name(),
                                Jira.Browser.Firefox.name()
                        )
                )
        );

        inputSummary.setText(
                settings.getProperty(
                        Settings.Keys.SummaryFieldMapping.name(),
                        "[$A] - $B")
        );
        inputDescription.setText(
                settings.getProperty(
                        Settings.Keys.DescriptionFieldMapping.name(),
                        "$C") //NOI18N
        );
        inputStepName.setText(
                settings.getProperty(
                        Settings.Keys.TestStepNameFieldMapping.name(),
                        "$D") //NOI18N
        );
        inputStepData.setText(
                settings.getProperty(
                        Settings.Keys.TestDataFieldMapping.name(),
                        "$E") //NOI18N
        );
        inputStepExpectedResult.setText(
                settings.getProperty(
                        Settings.Keys.ExpectedResultFieldMapping.name(),
                        "$F") //NOI18N
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeadline = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        selectBrowser = new javax.swing.JComboBox<>();
        jButtonOpenBrowser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buttonCheckTestCreatePage = new javax.swing.JButton();
        labelTestCreatePageResult = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputSummary = new javax.swing.JTextField();
        inputDescription = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputStepData = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputStepExpectedResult = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        buttonSelectFile = new javax.swing.JButton();
        labelExcelFile = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonLoad = new javax.swing.JButton();
        inputStepName = new javax.swing.JTextField();
        buttonExport = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        labelLoad = new javax.swing.JLabel();
        labelExport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHeadline.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de_DE"); // NOI18N
        jLabelHeadline.setText(bundle.getString("ZEPHYR TESTFALL IMPORTER")); // NOI18N
        jLabelHeadline.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText(bundle.getString("WÄHLEN SIE EINEN BROWSER")); // NOI18N

        selectBrowser.setModel(new DefaultComboBoxModel(Jira.Browser.values()));
        selectBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBrowserActionPerformed(evt);
            }
        });

        jButtonOpenBrowser.setText(bundle.getString("BROWSER ÖFFNEN")); // NOI18N
        jButtonOpenBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenBrowserActionPerformed(evt);
            }
        });

        jLabel4.setText("2. In Jira Anmelden und im Zephyr-Menü \"Tests\" den Punkt \"Create a Test\" öffnen");

        buttonCheckTestCreatePage.setText(bundle.getString("CHECK TEST CREATE PAGE")); // NOI18N
        buttonCheckTestCreatePage.setToolTipText("");
        buttonCheckTestCreatePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckTestCreatePageActionPerformed(evt);
            }
        });

        labelTestCreatePageResult.setText("   ");

        jLabel5.setText("<html>3. Feldverknüpfung: Geben Sie in die Zielfelder unten, die Quell-Spaltennamen in der <br>Form \"[$A] - [$B] / $C\" ein. Mögliche werte: $A - $F und $SHEET</html> ");

        jLabel1.setText(bundle.getString("SUMMARY")); // NOI18N

        jLabel3.setText(bundle.getString("DESCRIPTION")); // NOI18N

        inputSummary.setText("[$SHEET] $A - $B");
        inputSummary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputSummaryFocusLost(evt);
            }
        });

        inputDescription.setText("$C");
        inputDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputDescriptionFocusLost(evt);
            }
        });

        jLabel6.setText(bundle.getString("TEST STEP")); // NOI18N
        jLabel6.setToolTipText("");

        jLabel7.setText(bundle.getString("TEST DATA")); // NOI18N
        jLabel7.setToolTipText("");

        inputStepData.setText("$E");
        inputStepData.setToolTipText("");
        inputStepData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputStepDataFocusLost(evt);
            }
        });

        jLabel8.setText(bundle.getString("EXPECTED RESULT")); // NOI18N
        jLabel8.setToolTipText("");

        inputStepExpectedResult.setText("$F");
        inputStepExpectedResult.setToolTipText("");
        inputStepExpectedResult.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputStepExpectedResultFocusLost(evt);
            }
        });

        jLabel9.setText(bundle.getString("4. AUSWAHL DER INPUT-DATEI")); // NOI18N

        buttonSelectFile.setText(bundle.getString("DATEI AUSWÄHLEN...")); // NOI18N
        buttonSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectFileActionPerformed(evt);
            }
        });

        labelExcelFile.setText("   ");

        buttonLoad.setText(bundle.getString("DATEN AUS EXCELDATEI LESEN")); // NOI18N
        buttonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadActionPerformed(evt);
            }
        });

        inputStepName.setText("$D");
        inputStepName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputStepNameFocusLost(evt);
            }
        });

        buttonExport.setText(bundle.getString("DATEN INS JIRA SCHREIBEN")); // NOI18N
        buttonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportActionPerformed(evt);
            }
        });

        labelLoad.setText("   ");

        labelExport.setText("   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectBrowser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSummary)
                            .addComponent(inputDescription)
                            .addComponent(inputStepData)
                            .addComponent(inputStepExpectedResult)
                            .addComponent(inputStepName))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1)
                                .addGap(0, 0, 0))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonLoad)
                                .addGap(18, 18, 18)
                                .addComponent(labelLoad))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(buttonSelectFile)
                                .addGap(18, 18, 18)
                                .addComponent(labelExcelFile))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonCheckTestCreatePage)
                                .addGap(18, 18, 18)
                                .addComponent(labelTestCreatePageResult))
                            .addComponent(jButtonOpenBrowser)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonExport)
                        .addGap(18, 18, 18)
                        .addComponent(labelExport)
                        .addGap(0, 0, 0))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOpenBrowser)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCheckTestCreatePage)
                    .addComponent(labelTestCreatePageResult))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputStepName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputStepData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputStepExpectedResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSelectFile)
                    .addComponent(labelExcelFile))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLoad))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelExport))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelHeadline)
                .addContainerGap(343, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportActionPerformed

        if (jira != null
                && jira.getUrlTestCreatePage() != null
                && excel2TestcaseConverter != null
                && excel2TestcaseConverter.getTestcases() != null
                && excel2TestcaseConverter.getTestcases().size() > 0) {

            Task task = new Task();
            task.addPropertyChangeListener(this);
            task.execute();

        }
    }//GEN-LAST:event_buttonExportActionPerformed

    private void inputStepNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputStepNameFocusLost
        Settings settings = Settings.getInstance();
        settings.setProperty(
                Settings.Keys.TestStepNameFieldMapping.name(),
                inputStepName.getText());
        settings.store();
    }//GEN-LAST:event_inputStepNameFocusLost

    private void buttonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadActionPerformed
        // Reset
        excel2TestcaseConverter = null;
        importFileLoaded = false;
        jProgressBar1.setValue(0);
        labelExport.setText("");
        updateActiveStatusForExportButton();

        excel2TestcaseConverter = new Excel2TestcaseConverter(
                inputSummary.getText(),
                inputDescription.getText(),
                inputStepName.getText(),
                inputStepData.getText(),
                inputStepExpectedResult.getText(),
                excelFile);

        labelLoad.setText("");
        if (excel2TestcaseConverter.parse() != null) {
            importFileLoaded = true;
            labelLoad.setText(java.util.ResourceBundle.getBundle("de_DE").getString("ERFOLGREICH $X TESTFÄLLE GELADEN!").
                    replace("$x", Integer.toString(
                            excel2TestcaseConverter.getTestcases().size()
                    )));
        }
        updateActiveStatusForExportButton();
    }//GEN-LAST:event_buttonLoadActionPerformed

    private void buttonSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectFileActionPerformed

        Settings settings = Settings.getInstance();
        String startPath = settings.getProperty(
                Settings.Keys.ExcelFilePath.name()
        );

        if (startPath == null || startPath.isEmpty()) {
            excelFile = ExcelFile.openFileChooser();
        } else {
            excelFile = ExcelFile.openFileChooser(startPath);
        }

        importFileLoadable = (excelFile != null && excelFile.testExcelFile());
        updateActiveStatusForLoadButton();

        if (importFileLoadable) {
            settings.setProperty(
                    Settings.Keys.ExcelFilePath.name(),
                    new File(excelFile.getPath()).getParent());
            settings.store();
            
            labelExcelFile.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("de_DE").getString("File kann geladen werden"), new Object[]{excelFile.getType().name()}));
        } else {
            labelExcelFile.setText(java.util.ResourceBundle.getBundle("de_DE").getString("FILE KANN NICHT GELADEN WERDEN. BITTE ANDERES WÄHLEN."));
        }
        
        updateActiveStatusForExportButton();
        updateActiveStatusForLoadButton();
    }//GEN-LAST:event_buttonSelectFileActionPerformed

    private void inputStepExpectedResultFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputStepExpectedResultFocusLost
        Settings settings = Settings.getInstance();
        settings.setProperty(
                Settings.Keys.ExpectedResultFieldMapping.name(),
                inputStepExpectedResult.getText());
        settings.store();
    }//GEN-LAST:event_inputStepExpectedResultFocusLost

    private void inputStepDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputStepDataFocusLost
        Settings settings = Settings.getInstance();
        settings.setProperty(
                Settings.Keys.TestDataFieldMapping.name(),
                inputStepData.getText());
        settings.store();
    }//GEN-LAST:event_inputStepDataFocusLost

    private void inputDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputDescriptionFocusLost
        Settings settings = Settings.getInstance();
        settings.setProperty(
                Settings.Keys.DescriptionFieldMapping.name(),
                inputDescription.getText());
        settings.store();
    }//GEN-LAST:event_inputDescriptionFocusLost

    private void inputSummaryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSummaryFocusLost
        Settings settings = Settings.getInstance();
        settings.setProperty(
                Settings.Keys.SummaryFieldMapping.name(),
                inputSummary.getText());
        settings.store();
    }//GEN-LAST:event_inputSummaryFocusLost

    private void buttonCheckTestCreatePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckTestCreatePageActionPerformed

        if (jira == null || !browserWorks) {
            labelTestCreatePageResult.setText(java.util.ResourceBundle.getBundle("de_DE").getString("ZUERST BROWSER ÖFFNEN UND OFFEN LASSEN"));
            testCreatePageOpened = false;
        } else if (jira.testCreatePageOpened()) {
            labelTestCreatePageResult.setText(java.util.ResourceBundle.getBundle("de_DE").getString("<HTML>TEST CREATE PAGE ERKANNT! <FONT COLOR=GREEN>OK!</FONT></HTML>"));
            testCreatePageOpened = true;
        } else {
            labelTestCreatePageResult.setText(java.util.ResourceBundle.getBundle("de_DE").getString("TEST CREATE PAGE WURDE NICHT ERKANNT. BITTE SCHRITT 2 WIEDERHOLEN"));
            testCreatePageOpened = false;
        }

        updateActiveStatusForExportButton();
    }//GEN-LAST:event_buttonCheckTestCreatePageActionPerformed

    private void jButtonOpenBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenBrowserActionPerformed

        Jira.Browser selectedBrowser = null;

        if (selectBrowser.getSelectedObjects().length >= 1) {
            selectedBrowser = (Jira.Browser) selectBrowser.getSelectedObjects()[0];
        }

        jira = new Jira(selectedBrowser);

        browserWorks = jira.testBrowserOpen();
    }//GEN-LAST:event_jButtonOpenBrowserActionPerformed

    private void selectBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBrowserActionPerformed
        Settings settings = Settings.getInstance();
        settings.setProperty(Settings.Keys.Browser.name(), selectBrowser.getSelectedItem().toString());
        settings.store();
    }//GEN-LAST:event_selectBrowserActionPerformed

    private boolean testCreatePageOpened = false;
    private boolean importFileLoaded = false;

    private void updateActiveStatusForExportButton() {
        if (!testCreatePageOpened || !importFileLoaded) {
            buttonExport.setEnabled(false);
            labelExport.setText("");
        } else {
            buttonExport.setEnabled(true);
        }

    }

    private boolean importFileLoadable = false;

    private void updateActiveStatusForLoadButton() {
        buttonLoad.setEnabled(importFileLoadable);
        if(!importFileLoadable) {
            labelLoad.setText("");
        }
    }

    private ExcelFile excelFile = null;
    private Excel2TestcaseConverter excel2TestcaseConverter = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equalsIgnoreCase(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    /**
     * Listens on Progress changes
     *
     * @param evt
     */
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equalsIgnoreCase("progress")) {
            int progress = (Integer) evt.getNewValue();
            jProgressBar1.setValue(progress);
        }
    }

    class Task extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            float index = 0;
            int progress = 0;
            float count = excel2TestcaseConverter.getTestcases().size();

            setProgress(progress);
            for (JiraTestcase testcase : excel2TestcaseConverter.getTestcases()) {
                jira.createIssue(testcase);
//                try {
//                    Thread.sleep(100);
//                } catch (Exception ignore) {
//                }
                index++;
                progress = ((Float) (Math.min((index / count) * 100.00f, 100.00f))).intValue();
                setProgress(progress);
            }
            return null;
        }

        @Override
        protected void done() {
            labelExport.setText(java.util.ResourceBundle.getBundle("de_DE").getString("ExportErfolgreich"));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCheckTestCreatePage;
    private javax.swing.JButton buttonExport;
    private javax.swing.JButton buttonLoad;
    private javax.swing.JButton buttonSelectFile;
    private javax.swing.JTextField inputDescription;
    private javax.swing.JTextField inputStepData;
    private javax.swing.JTextField inputStepExpectedResult;
    private javax.swing.JTextField inputStepName;
    private javax.swing.JTextField inputSummary;
    private javax.swing.JButton jButtonOpenBrowser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHeadline;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelExcelFile;
    private javax.swing.JLabel labelExport;
    private javax.swing.JLabel labelLoad;
    private javax.swing.JLabel labelTestCreatePageResult;
    private javax.swing.JComboBox<Jira.Browser> selectBrowser;
    // End of variables declaration//GEN-END:variables
}
